### ISSUE TITLE
Not working with Nx

### ISSUE THREAD

**Issue by binoypatel** [DevExpress/devextreme-schematics#77]
Hi 

I am trying to add template on monorepo generated by Nx (ngrx workspace). It update all files etc. without any error, ng serve doesn't show any error. When I open the application it simply doesn't show anything, no error in chrome developer tools. Looks like some misalignment between template and nx. 

Can you pl help?

Thanks,
Binoy

**Comment by dxvladislavvolkov** [comment]
Hi,
Would you please clarify what steps you used to create the template, specify the NPM\Yarn commands you used to install our application, and the results you received after each command?
I tried it using the following steps:
1. ng new app1 --directory=app1 --collection=@nrwl/schematics
2. ng generate @nrwl/schematics:application myapp
3. devextreme add angular-template --resolve-conflicts=override

and discovered a wrong selector prefix in app.component.ts. It's fixed in the [pr](https://github.com/DevExpress/devextreme-schematics/pull/76).

**Comment by binoypatel** [comment]
Hi

Thanks for your reply, I am using Yarn and here are my commands:

1. ng new apps-workspace --collection=@nrwl/schematics
2. ng generate app servicepro --routing --style=scss
3. ng add @angular/pwa --project app
4. yarn add devextreme-angular
5. ng g devextreme-angular:add-app-template --project=app

I am not using devextreme though, I will try and see if it works.


Thanks,
Binoy

**Comment by binoypatel** [comment]
Hi Vlad

You are right it got wrong prefix that cause the issue. After changing it manually it started working

Thanks
Binoy
